### ISSUE TITLE
Node Panic: Storage root must match that calculated

### ISSUE THREAD

**Issue by carumusan** [hicommonwealth/edgeware-node#107]
```
2019-09-14T20:31:34.413724638Z    0: substrate_panic_handler::set::{{closure}}::hc68c8cd4dd6a3e1f (0x561341daf2b0)
 A 
2019-09-14T20:31:34.414824415Z    1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x561341eecd69)
 A 
2019-09-14T20:31:34.415410802Z              at src/libstd/panicking.rs:481
 A 
2019-09-14T20:31:34.416456644Z    2: std::panicking::begin_panic::hf23aecaf1a86cff2 (0x5613418017d5)
 A 
2019-09-14T20:31:34.420154474Z    3: <edgeware_runtime::Runtime as substrate_client::runtime_api::runtime_decl_for_Core::Core<sr_primitives::generic::block::Block<sr_primitives::generic::header::Header<u32,sr_primitives::traits::BlakeTwo256>,sr_primitives::generic::unchecked_extrinsic::UncheckedExtrinsic<<srml_indices::Module<edgeware_runtime::Runtime> as sr_primitives::traits::StaticLookup>::Source,edgeware_runtime::Call,sr_primitives::AnySignature,(srml_system::CheckVersion<edgeware_runtime::Runtime>, srml_system::CheckGenesis<edgeware_runtime::Runtime>, srml_system::CheckEra<edgeware_runtime::Runtime>, srml_system::CheckNonce<edgeware_runtime::Runtime>, srml_system::CheckWeight<edgeware_runtime::Runtime>, srml_balances::TakeFees<edgeware_runtime::Runtime>)>>>>::execute_block::hc5566aed87bf9cd3 (0x56134180ad14)
 A 
2019-09-14T20:31:34.420176410Z    4: edgeware_runtime::api::dispatch::h0ef5fad77544a537 (0x56134180bb95)
 A 
2019-09-14T20:31:34.420181346Z    5: std::panicking::try::do_call::h11891d9045d598ee (0x561341800192)
 A 
2019-09-14T20:31:34.420185376Z    6: __rust_maybe_catch_panic (0x561341ef194a)
 A 
2019-09-14T20:31:34.420189175Z              at src/libpanic_unwind/lib.rs:82
 A 
2019-09-14T20:31:34.420206615Z    7: substrate_executor::native_executor::safe_call::hd00037995500e6c1 (0x5613417fff38)
 A 
2019-09-14T20:31:34.420210952Z    8: std::thread::local::LocalKey<T>::with::h147a711b2f0fe6c2 (0x5613417ffb48)
 A 
2019-09-14T20:31:34.420215167Z    9: <edgeware_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::h282a322b2454e10e (0x5613417ff6dd)
 A 
2019-09-14T20:31:34.423270268Z   10: std::thread::local::LocalKey<T>::with::hd45ba08e97c618a2 (0x561340c1d9ee)
 A 
2019-09-14T20:31:34.426170282Z   11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h2f7fef50081fa3bd (0x561341122b66)
 A 
2019-09-14T20:31:34.428900832Z   12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::ha022fb9fa86281ea (0x56134117d232)
 A 
2019-09-14T20:31:34.430476555Z   13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h513b9dd7135d2b8f (0x561341142c9b)
 A 
2019-09-14T20:31:34.432726352Z   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::he1056afbaf70bb47 (0x5613410a66d3)
 A 
2019-09-14T20:31:34.434398014Z   15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}::he2b7352e7ba8fe71 (0x561340c95395)
 A 
2019-09-14T20:31:34.434414682Z   16: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h35060bca5e9cc3c7 (0x561340c7ef97)
 A 
2019-09-14T20:31:34.436093662Z   17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h3e399afa81762622 (0x561341267162)
 A 
2019-09-14T20:31:34.436110992Z   18: substrate_consensus_common::import_queue::import_single_block::h00592621549713f3 (0x561340da9e2f)
 A 
2019-09-14T20:31:34.437782346Z   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h7eede058d8da248f (0x5613411a532a)
 A 
2019-09-14T20:31:34.439733973Z   20: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll::he10d19f3275b29e9 (0x561340ac6381)
 A 
2019-09-14T20:31:34.441951415Z   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::hd6eb2ef26148776e (0x5613411a57fb)
 A 
2019-09-14T20:31:34.443147203Z   22: futures_executor::thread_pool::PoolState::work::h128efd25449415f6 (0x561341d77306)
 A 
2019-09-14T20:31:34.444608658Z   23: std::sys_common::backtrace::__rust_begin_short_backtrace::h009b6dccb9e1ba20 (0x561341d79254)
 A 
2019-09-14T20:31:34.445749832Z   24: std::panicking::try::do_call::h944d2744c24a8faf (0x561341d74635)
 A 
2019-09-14T20:31:34.446121342Z   25: __rust_maybe_catch_panic (0x561341ef194a)
 A 
2019-09-14T20:31:34.446330384Z              at src/libpanic_unwind/lib.rs:82
 A 
2019-09-14T20:31:34.447429822Z   26: core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b530351a40c2059 (0x561341d7629a)
 A 
2019-09-14T20:31:34.447441028Z   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x561341edb48f)
 A 
2019-09-14T20:31:34.447445562Z              at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
 A 
2019-09-14T20:31:34.447910007Z   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x561341ef0cd0)
 A 
2019-09-14T20:31:34.447944073Z              at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
 A 
2019-09-14T20:31:34.447948494Z       std::sys_common::thread::start_thread::h2613204ce513782e
 A 
2019-09-14T20:31:34.447951963Z              at src/libstd/sys_common/thread.rs:13
 A 
2019-09-14T20:31:34.448265123Z       std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
 A 
2019-09-14T20:31:34.448281572Z              at src/libstd/sys/unix/thread.rs:79
 A 
2019-09-14T20:31:34.448285384Z   29: start_thread (0x7f9974e2e6db)
 A 
2019-09-14T20:31:34.448288632Z   30: __clone (0x7f997493f88f)
 A 
2019-09-14T20:31:34.448291967Z   31: <unknown> (0x0)
 A 
2019-09-14T20:31:34.448295657Z 
 A 
2019-09-14T20:31:34.448298963Z Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-25d0b09b83fafc89/2a80448/srml/executive/src/lib.rs:319
 A 
```

**Comment by carumusan** [comment]
Related: https://github.com/paritytech/substrate/issues/3580
