### ISSUE TITLE
ExtrinsicStatus:: 1010: Invalid Transaction: Payment

### ISSUE THREAD

**Issue by danielimkk** [hicommonwealth/edgeware-node#139]
Hello. I've been trying to stake using edgeware-cli. It seems everything should be ok, but when you try to stake or transfer some amount of EDG it returns an error: 
`Making tx: staking.bond(["5FpusSiSw1n341negr65EfMj98A26JY4ajxEDYdrfhWpCLSs","0.000000000000000020","Staked"])
[ '5FpusSiSw1n341negr65EfMj98A26JY4ajxEDYdrfhWpCLSs', '20', 'Staked' ]
2020-02-19 17:50:26        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
2020-02-19 17:50:26             DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
    at errorHandler (/home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:234:26)
    at /home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:214:9
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Failed:  Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
    at errorHandler (/home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:234:26)
    at /home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:214:9
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
`

Could you please tell me what could be an issue?

**Comment by drewstone** [comment]
This repo isn't for the edgeware-cli. Could you please repost in there?

**Comment by danielimkk** [comment]
Sure, reposted
