### ISSUE TITLE
many types cannot be found when run a simple case in edge node

### ISSUE THREAD

**Issue by past2017** [hicommonwealth/edgeware-node#142]
edgeware-node version: **Edgeware Node v3.0.1**
polkadot-api: **polkadot/api@1.3.1**
when run a simple case as below:
```
const { ApiPromise, WsProvider } = require('@polkadot/api');
async function main () {
    // Initialise the provider to connect to the local node
    const provider = new WsProvider('ws://127.0.0.1:9944');
    // Create the API and wait until ready
    const api = await ApiPromise.create({ provider });
    // Retrieve the chain & node information information via rpc calls
    const [chain, nodeName, nodeVersion] = await Promise.all([
            api.rpc.system.chain(),
            api.rpc.system.name(),
            api.rpc.system.version()
    ]);
    console.log(`You are connected to chain ${chain} using ${nodeName} v${nodeVersion}`);
}

```

**some error is found , the last line is the expected result:**
```
Error: Unable to find plain type for {"info":6,"type":"VoteType"}
    at TypeRegistry.getOrThrow (/root/src2/node_modules/@polkadot/types/create/registry.js:190:13)
    at 6 (/root/src2/node_modules/@polkadot/types/create/createClass.js:122:61)
    at getTypeClass (/root/src2/node_modules/@polkadot/types/create/createClass.js:167:10)
    at typeDef.map.typeDef (/root/src2/node_modules/@polkadot/types/create/registry.js:64:70)
    at Array.map (<anonymous>)
    at section.events.unwrap.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:64:25)
    at Array.forEach (<anonymous>)
    at metadata.asLatest.modules.filter.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:57:29)
    at Array.forEach (<anonymous>)
    at decorateEvents (/root/src2/node_modules/@polkadot/types/create/registry.js:55:24)
Error: Unable to find plain type for {"info":6,"type":"VoteStage"}
    at TypeRegistry.getOrThrow (/root/src2/node_modules/@polkadot/types/create/registry.js:190:13)
    at 6 (/root/src2/node_modules/@polkadot/types/create/createClass.js:122:61)
    at getTypeClass (/root/src2/node_modules/@polkadot/types/create/createClass.js:167:10)
    at typeDef.map.typeDef (/root/src2/node_modules/@polkadot/types/create/registry.js:64:70)
    at Array.map (<anonymous>)
    at section.events.unwrap.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:64:25)
    at Array.forEach (<anonymous>)
    at metadata.asLatest.modules.filter.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:57:29)
    at Array.forEach (<anonymous>)
    at decorateEvents (/root/src2/node_modules/@polkadot/types/create/registry.js:55:24)
Error: Unable to find plain type for {"info":6,"type":"Balance2"}
    at TypeRegistry.getOrThrow (/root/src2/node_modules/@polkadot/types/create/registry.js:190:13)
    at 6 (/root/src2/node_modules/@polkadot/types/create/createClass.js:122:61)
    at getTypeClass (/root/src2/node_modules/@polkadot/types/create/createClass.js:167:10)
    at typeDef.map.typeDef (/root/src2/node_modules/@polkadot/types/create/registry.js:64:70)
    at Array.map (<anonymous>)
    at section.events.unwrap.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:64:25)
    at Array.forEach (<anonymous>)
    at metadata.asLatest.modules.filter.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:57:29)
    at Array.forEach (<anonymous>)
    at decorateEvents (/root/src2/node_modules/@polkadot/types/create/registry.js:55:24)
Error: Unable to find plain type for {"info":6,"type":"VoteType"}
    at TypeRegistry.getOrThrow (/root/src2/node_modules/@polkadot/types/create/registry.js:190:13)
    at 6 (/root/src2/node_modules/@polkadot/types/create/createClass.js:122:61)
    at getTypeClass (/root/src2/node_modules/@polkadot/types/create/createClass.js:167:10)
    at typeDef.map.typeDef (/root/src2/node_modules/@polkadot/types/create/registry.js:64:70)
    at Array.map (<anonymous>)
    at section.events.unwrap.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:64:25)
    at Array.forEach (<anonymous>)
    at metadata.asLatest.modules.filter.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:57:29)
    at Array.forEach (<anonymous>)
    at decorateEvents (/root/src2/node_modules/@polkadot/types/create/registry.js:55:24)
Error: Unable to find plain type for {"info":6,"type":"VoteStage"}
    at TypeRegistry.getOrThrow (/root/src2/node_modules/@polkadot/types/create/registry.js:190:13)
    at 6 (/root/src2/node_modules/@polkadot/types/create/createClass.js:122:61)
    at getTypeClass (/root/src2/node_modules/@polkadot/types/create/createClass.js:167:10)
    at typeDef.map.typeDef (/root/src2/node_modules/@polkadot/types/create/registry.js:64:70)
    at Array.map (<anonymous>)
    at section.events.unwrap.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:64:25)
    at Array.forEach (<anonymous>)
    at metadata.asLatest.modules.filter.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:57:29)
    at Array.forEach (<anonymous>)
    at decorateEvents (/root/src2/node_modules/@polkadot/types/create/registry.js:55:24)
Error: Unable to find plain type for {"info":6,"type":"Balance2"}
    at TypeRegistry.getOrThrow (/root/src2/node_modules/@polkadot/types/create/registry.js:190:13)
    at 6 (/root/src2/node_modules/@polkadot/types/create/createClass.js:122:61)
    at getTypeClass (/root/src2/node_modules/@polkadot/types/create/createClass.js:167:10)
    at typeDef.map.typeDef (/root/src2/node_modules/@polkadot/types/create/registry.js:64:70)
    at Array.map (<anonymous>)
    at section.events.unwrap.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:64:25)
    at Array.forEach (<anonymous>)
    at metadata.asLatest.modules.filter.forEach (/root/src2/node_modules/@polkadot/types/create/registry.js:57:29)
    at Array.forEach (<anonymous>)
    at decorateEvents (/root/src2/node_modules/@polkadot/types/create/registry.js:55:24)
Unknown types found, no types for Balance2,ProposalContents,ProposalRecord,ProposalTitle,VoteOutcome,VoteRecord,VoteStage,VoteType,voting::TallyType,voting::VoteType
You are connected to chain Edgeware using Edgeware Node v3.0.1
```

**Comment by drewstone** [comment]
Yes, you need to use the [edgeware-node-types](https://github.com/hicommonwealth/edgeware-node-types) in addition to the Polkadot API types. An example can be found there.
