### ISSUE TITLE
Hardhat EVM deployment issue (same issue resolved on Moonbeam)

### ISSUE THREAD

**Issue by alanzhong** [hicommonwealth/edgeware-node#294]
Running into the same issue that was addressed by Moonbeam earlier this year:
- https://github.com/PureStake/moonbeam/issues/146
- https://github.com/vporton/moonbeam-deploy-bug

Joel commented
"Thank you for the detailed bug issue. We found the problem, which was related to web3_clientVersion method. Will be fixed soon. I will keep you posted." 

`$ npx hardhat run deploy/sample.js --network moonbasealpha
ProviderError: Method not found
    at HttpProvider.request (/home/porton/t/moonbeam-deploy-bug/node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
    at LocalAccountsProvider.request (/home/porton/t/moonbeam-deploy-bug/node_modules/hardhat/src/internal/core/providers/accounts.ts:131:34)
    at GanacheGasMultiplierProvider._isGanache (/home/porton/t/moonbeam-deploy-bug/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:175:30)
    at GanacheGasMultiplierProvider.request (/home/porton/t/moonbeam-deploy-bug/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:164:23)
    at EthersProviderWrapper.send (/home/porton/t/moonbeam-deploy-bug/node_modules/@nomiclabs/hardhat-ethers/src/ethers-provider-wrapper.ts:13:20)
    at Object.getSigners (/home/porton/t/moonbeam-deploy-bug/node_modules/@nomiclabs/hardhat-ethers/src/helpers.ts:35:20)
    at getContractFactoryByAbiAndBytecode (/home/porton/t/moonbeam-deploy-bug/node_modules/@nomiclabs/hardhat-ethers/src/helpers.ts:250:21)
    at main (/home/porton/t/moonbeam-deploy-bug/deploy/sample.js:3:21)
`

**Comment by alanzhong** [comment]
Adding Web3Api seems to be the fix

https://github.com/PureStake/moonbeam/commit/f12b8ae46a150ea9c943cec4cd204e89deffc5f9?branch=f12b8ae46a150ea9c943cec4cd204e89deffc5f9&diff=split

![image](https://user-images.githubusercontent.com/4783653/116759391-102e7c00-a9c7-11eb-9853-781cf7e7353a.png)

**Comment by alanzhong** [comment]
Associated test: https://github.com/PureStake/moonbeam/commit/ae8c28e2eae94654d40fcbfaff6ba28562bea669

**Comment by drewstone** [comment]
Thanks for the research! @alanzhong I'd welcome a PR to address this fix.
