### ISSUE TITLE
After build a new install and try to sync from scratch node stuck and not sync. 

### ISSUE THREAD

**Issue by iammelea** [hicommonwealth/edgeware-node#81]
```
stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::hdf48ac2af1602953 (0x55f9586cef70)
   1: std::panicking::rust_panic_with_hook::h057ff03eb4c8000f (0x55f9587f3a99)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::h805af19745166306 (0x55f957d43525)
   3: srml_executive::Executive<System,Block,Context,Payment,UnsignedValidator,AllModules>::execute_block::h1faa08467bc1d3e7 (0x55f957de3844)
   4: edgeware_runtime::api::dispatch::heb9689523d165f94 (0x55f957d4c71f)
   5: std::panicking::try::do_call::h755ad578dd3340ba (0x55f957d41c52)
   6: __rust_maybe_catch_panic (0x55f9587f8e2a)
             at src/libpanic_unwind/lib.rs:85
   7: substrate_executor::native_executor::safe_call::hdf2eb807a03c8bf6 (0x55f957d41cca)
   8: std::thread::local::LocalKey<T>::with::h3c9716d9a94d11a0 (0x55f957d41817)
   9: <edgeware_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hbde3b7547d93e077 (0x55f957d4139d)
  10: std::thread::local::LocalKey<T>::with::hd2879aad0a097a2c (0x55f957cad36f)
  11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h49b3eb6a0d9758b7 (0x55f95795e6a9)
  12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::hf2a82bcdd7af0a5b (0x55f9579ad8b2)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h322f0ef27ab31b2c (0x55f957979db2)
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h7bf9c43d8523f12f (0x55f957cf6872)
  15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}::h6f411f37aae6c613 (0x55f957b22b0c)
  16: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hed0638642bb1ef27 (0x55f957b0a63c)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h0862877dd283b194 (0x55f9578d6f2f)
  18: substrate_consensus_common::import_queue::import_single_block::h9b091286f59c262b (0x55f957a34c6d)
  19: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::hf21b822975f839d1 (0x55f957b5da64)
  20: futures::task_impl::std::set::h8e3845bde1c2aef2 (0x55f958566e72)
  21: std::panicking::try::do_call::h91690f0b7e0ef0b6 (0x55f9585668d2)
  22: __rust_maybe_catch_panic (0x55f9587f8e2a)
             at src/libpanic_unwind/lib.rs:85
  23: tokio_threadpool::task::Task::run::h4bcb5aec8c76b267 (0x55f958563f39)
  24: tokio_threadpool::worker::Worker::run_task::ha7342d0a4f9e9e56 (0x55f95855d8a5)
  25: tokio_threadpool::worker::Worker::run::h7daf2f70398dc227 (0x55f95855cd9e)
  26: std::thread::local::LocalKey<T>::with::h0101df3fa466f0ac (0x55f95854757e)
  27: std::thread::local::LocalKey<T>::with::hbec4728efa3494e5 (0x55f95854785f)
  28: std::thread::local::LocalKey<T>::with::he6b26374f55d3b69 (0x55f9585479eb)
  29: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h47bf9032e8a6467f (0x55f9585485be)
  30: std::thread::local::LocalKey<T>::with::hbacc7cca07cce3b3 (0x55f958567c83)
  31: std::thread::local::LocalKey<T>::with::h54c51c6f8e55edbd (0x55f95856750e)
  32: std::sys_common::backtrace::__rust_begin_short_backtrace::h810908f96fb97814 (0x55f95855f481)
  33: std::panicking::try::do_call::h87626edd0c074712 (0x55f95856682c)
  34: __rust_maybe_catch_panic (0x55f9587f8e2a)
             at src/libpanic_unwind/lib.rs:85
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}::h8ff33e4441011336 (0x55f9585600e0)
  36: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05 (0x55f9587e0bdf)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3 (0x55f9587f8140)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
      std::sys_common::thread::start_thread::ha32838ccbb8a8179
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
             at src/libstd/sys/unix/thread.rs:79
  38: start_thread (0x7f63d5f186ba)
  39: clone (0x7f63d5a3841d)
  40: <unknown> (0x0)

Thread 'main-tokio-1' panicked at 'Transaction trie root must be valid.', /home/putamadre/.cargo/git/checkouts/substrate-7e08433d4c370a21/1cfb794/srml/executive/src/lib.rs:189

This is a bug. Please report it at:

	https://github.com/hicommonwealth/edgeware-node/issues/new

Hash not equal
acb8eef08096c4a26b919474eb012518fd942377d52d91972ebd0b3a9e5d5382
03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314
/Users/drewstone/.cargo/git/checkouts/substrate-7e08433d4c370a21/1cfb794/srml/executive/src/lib.rs
189
3
2019-07-30 15:51:30 Syncing 19.7 bps, target=#213708 (2 peers), best: #256 (0x4904…4be4), finalized #0 (0x59d4…b157), ⬇ 86.1kiB/s ⬆ 3.3kiB/s
2019-07-30 15:51:30 Syncing, target=#213708 (2 peers), best: #256 (0x4904…4be4), finalized #0 (0x59d4…b157), ⬇ 86.1kiB/s ⬆ 3.3kiB/s
Hash: given=37aeec6f56b01441f490df49592a9af93d1413b338d4e6163acd513057f3aaac, expected=03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314



====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::hdf48ac2af1602953 (0x55f9586cef70)
   1: std::panicking::rust_panic_with_hook::h057ff03eb4c8000f (0x55f9587f3a99)
             at src/libstd/panicking.rs:478
   2: std::panicking::begin_panic::h805af19745166306 (0x55f957d43525)
   3: srml_executive::Executive<System,Block,Context,Payment,UnsignedValidator,AllModules>::execute_block::h1faa08467bc1d3e7 (0x55f957de3844)
   4: edgeware_runtime::api::dispatch::heb9689523d165f94 (0x55f957d4c71f)
   5: std::panicking::try::do_call::h755ad578dd3340ba (0x55f957d41c52)
   6: __rust_maybe_catch_panic (0x55f9587f8e2a)
             at src/libpanic_unwind/lib.rs:85
   7: substrate_executor::native_executor::safe_call::hdf2eb807a03c8bf6 (0x55f957d41cca)
   8: std::thread::local::LocalKey<T>::with::h3c9716d9a94d11a0 (0x55f957d41817)
   9: <edgeware_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch::hbde3b7547d93e077 (0x55f957d4139d)
  10: std::thread::local::LocalKey<T>::with::hd2879aad0a097a2c (0x55f957cad36f)
  11: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h49b3eb6a0d9758b7 (0x55f95795e6a9)
  12: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_call_with_native_else_wasm_strategy::hf2a82bcdd7af0a5b (0x55f9579ad8b2)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h322f0ef27ab31b2c (0x55f957979db2)
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state::h7bf9c43d8523f12f (0x55f957cf6872)
  15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}::h6f411f37aae6c613 (0x55f957b22b0c)
  16: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::hed0638642bb1ef27 (0x55f957b0a63c)
  17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,PRA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block::h0862877dd283b194 (0x55f9578d6f2f)
  18: substrate_consensus_common::import_queue::import_single_block::h9b091286f59c262b (0x55f957a34c6d)
  19: <futures::future::poll_fn::PollFn<F> as futures::future::Future>::poll::hf21b822975f839d1 (0x55f957b5da64)
  20: futures::task_impl::std::set::h8e3845bde1c2aef2 (0x55f958566e72)
  21: std::panicking::try::do_call::h91690f0b7e0ef0b6 (0x55f9585668d2)
  22: __rust_maybe_catch_panic (0x55f9587f8e2a)
             at src/libpanic_unwind/lib.rs:85
  23: tokio_threadpool::task::Task::run::h4bcb5aec8c76b267 (0x55f958563f39)
  24: tokio_threadpool::worker::Worker::run_task::ha7342d0a4f9e9e56 (0x55f95855d8a5)
  25: tokio_threadpool::worker::Worker::run::h7daf2f70398dc227 (0x55f95855cd9e)
  26: std::thread::local::LocalKey<T>::with::h0101df3fa466f0ac (0x55f95854757e)
  27: std::thread::local::LocalKey<T>::with::hbec4728efa3494e5 (0x55f95854785f)
  28: std::thread::local::LocalKey<T>::with::he6b26374f55d3b69 (0x55f9585479eb)
  29: tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h47bf9032e8a6467f (0x55f9585485be)
  30: std::thread::local::LocalKey<T>::with::hbacc7cca07cce3b3 (0x55f958567c83)
  31: std::thread::local::LocalKey<T>::with::h54c51c6f8e55edbd (0x55f95856750e)
  32: std::sys_common::backtrace::__rust_begin_short_backtrace::h810908f96fb97814 (0x55f95855f481)
  33: std::panicking::try::do_call::h87626edd0c074712 (0x55f95856682c)
  34: __rust_maybe_catch_panic (0x55f9587f8e2a)
             at src/libpanic_unwind/lib.rs:85
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}::h8ff33e4441011336 (0x55f9585600e0)
  36: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h805c3cc89d534c05 (0x55f9587e0bdf)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h9ebda9db5f03daf3 (0x55f9587f8140)
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
      std::sys_common::thread::start_thread::ha32838ccbb8a8179
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h6f10b78f26c98dc6
             at src/libstd/sys/unix/thread.rs:79
  38: start_thread (0x7f63d5f186ba)
  39: clone (0x7f63d5a3841d)
  40: <unknown> (0x0)

Thread 'main-tokio-0' panicked at 'Transaction trie root must be valid.', /home/heyedgeware/.cargo/git/checkouts/substrate-7e08433d4c370a21/1cfb794/srml/executive/src/lib.rs:189

This is a bug. Please report it at:

	https://github.com/hicommonwealth/edgeware-node/issues/new

Hash not equal
dafc564bd1f4d6657d8c36843146094212c2e40aa97fd5c713da4ba3d04605ac
03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314
/Users/drewstone/.cargo/git/checkouts/substrate-7e08433d4c370a21/1cfb794/srml/executive/src/lib.rs
189
3
2019-07-30 15:51:34 Applying authority set change scheduled at block #700
2019-07-30 15:51:34 Applying GRANDPA set change to new set [(af9f319aa910050d7bed99f5ee2ba4e25429ac9e7746b94edcdf154b8a901a3c (5G2yXYTi...), 1), (705c8360296c7b6af2f842e7a0804492c86a855aaa605fdf419f577f1f4fecbe (5Ec2hh96...), 1), (5de1854fccd7bd5bf8abfcfd3e50bbeb05649c827a0cdefbd8ec02005b1ee4ef (5EBoJbE1...), 1), (f697b0a9e1401161380c5df2b3147646beb2bc0132f1c4b8bd8bdeb5f9532b2e (5He2hStV...), 1), (6a1e4860a31716685e0e0f49f3333c5799bbdab5dd3bb1e674134f6f9b2be689 (5ETqvphC...), 1), (333e04dd11f60ebf3037e2615be6d63b01f310b920f8022fb1d6737a2c73dfa5 (5DDtisex...), 1), (d0c50804164d9e79b3899df678d6de83a226b581fc972f8b8bdc74070ae7e8af (5GnSM7vx...), 1)]
2019-07-30 15:51:34 Rejected log entry because queue is full for "/dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F"
2019-07-30 15:51:34 Rejected log entry because queue is full for "/dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F"
2019-07-30 15:51:34 Rejected log entry because queue is full for "/dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F"
........
```
and then the node stuck in the same block and not sync new blocks anymore. cant close CTRL+c or pkill not work, CPU +100%

for solving this, stop / kill /reboot the server, do what you need for stop the process, then

```
cd .local/share/edgeware/chains/edgeware_testnet
rm -rf db/*
cd
cd edgeware-node
./target/release/edgeware --chain=edgeware --name nodename
```
If not sync, repeat again one more time and the node have to sync and cpu not 100%

**Comment by iammelea** [comment]
new soft update works
