### ISSUE TITLE
Validator node crashes occasionally

### ISSUE THREAD

**Issue by arjanz** [hicommonwealth/edgeware-node#98]
When trying to validate on testnet-v0.8, my validator node crashes after some time with the following message:

```
stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::hc68c8cd4dd6a3e1f (0x55f30990a070)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x55f309a47b29)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x55f309a475c2)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x55f309a474a6)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x55f309a6500d)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h90084b40e718c80d (0x55f308c423ae)
   6: wasmi::module::ModuleInstance::with_externvals::h158776f0d7664aab (0x55f3089c6fec)
   7: wasmi::module::ModuleInstance::new::hc72efd6e63c37954 (0x55f3089c7d50)
   8: substrate_executor::wasm_executor::WasmExecutor::instantiate_module::hfe681ed9361329af (0x55f3088c652a)
   9: substrate_executor::wasm_runtimes_cache::RuntimesCache::create_wasm_instance::hb5f52051f143a16b (0x55f308804149)
  10: substrate_executor::wasm_runtimes_cache::RuntimesCache::fetch_runtime::h8bea14bac0010b5d (0x55f3088003ac)
  11: std::thread::local::LocalKey<T>::with::h38c5e73dac506580 (0x55f308754b1b)
  12: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::runtime_version::h3d2640664f3c433e (0x55f308c14450)
  13: substrate_offchain_primitives::runtime_decl_for_OffchainWorkerApi::offchain_worker_call_api_at::ha198b51fa2e8232b (0x55f3089089c1)
  14: substrate_offchain_primitives::OffchainWorkerApi::offchain_worker_with_context::h85a657d9f36824be (0x55f30873b878)
  15: std::sys_common::backtrace::__rust_begin_short_backtrace::h606873de57c9ea59 (0x55f30867a1ae)
  16: std::panicking::try::do_call::h5ae20924acd27a19 (0x55f308ddadd4)
  17: __rust_maybe_catch_panic (0x55f309a4c70a)
             at src/libpanic_unwind/lib.rs:82
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}::hcf5e16830b78a967 (0x55f308682b83)
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x55f309a3624f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x55f309a4ba90)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  21: start_thread (0x7fb0e3ca56db)
  22: __clone (0x7fb0e37b688f)
  23: <unknown> (0x0)

Thread '<unnamed>' panicked at 'Due to validation `initial` and `maximum` should be valid: Memory("mmap returned an error")', src/libcore/result.rs:999
```

Is this due to memory limits? I have 4GB of memory allocated

**Comment by emielvanderhoek** [comment]
Perhaps also related to: https://github.com/hicommonwealth/edgeware-node/issues/93

**Comment by drewstone** [comment]
Yep, the current fix is to just run with more memory afaik. But I'm trying to diagnose this.
